### ISSUE TITLE
Any plans to update to Hec Ras 6.x version?

### ISSUE THREAD

**Issue by WindingWinter** [quantum-dan/raspy#2]
Hi,

Any plans to update to Hec Ras 6.x version?

**Comment by quantum-dan** [comment]
I'll look into it over the next few weeks.

**Comment by quantum-dan** [comment]
You can now specify a HEC-RAS version (using the current GitHub version) when you create a `Ras` object, e.g. `Ras(projectPath, which="631")`.  The few methods I've tested are still working, but let me know if any broke.  The updated version will be added to PyPI after another update I'm working on.

**Comment by quantum-dan** [comment]
The PyPI version now has that update as well.  I have updated the documentation with instructions.
