### ISSUE TITLE
Tutorial Notebooks or Videos for New Users

### ISSUE THREAD

**Issue by pmd84** [quantum-dan/raspy#3]
Hello, this looks like an incredibly promising way to interact with HEC-RAS. I have a reasonable grasp of Python code and use HEC-RAS GUI daily, but when navigating this Github page I cannot find easy-to-try examples of applying RasPy to my own HEC-RAS project for basic functions. It would be incredibly helpful if you had some follow-along jupyter notebooks or even YouTube videos showing basic functionality of RasPy to help get started. Would you be willing or able to do that? Thank you very much.

**Comment by quantum-dan** [comment]
Sure, I'll look into putting together a Jupyter notebook in the next few weeks.

**Comment by pmd84** [comment]
Incredible, thank you so much, Daniel. I will keep an eye out for those notebooks, and once I get the hang of it I will try to contribute some example notebooks of my own. 

Some actions I hope to accomplish in my workflow include: 
- Reading out WSE values for multiple profiles, reaches, and plans to log files for further analysis
- Adjusting manning's n values and bank stations along a cross section in an iterative way to influence water surface elevations and eliminate drawdowns
- Creating a flow file from a flow nodes shapefile (multiple profiles), and/or updating flow files when cross sections are moved or river stations change
- Incorporating Elevation Control Points from survey point shapefiles
- Adding structures from polyline shapefiles and altering bridge opening dimensions or culvert size / placement

If you are able to touch on any of those subjects, that would be a gift. If not, any additional tutorials you provide would be greatly appreciated.

**Comment by quantum-dan** [comment]
1, 2, and 3 will all be pretty straightforward and I'll definitely be able to do those.

I don't think 4 and 5 are supported by anything I have implemented, but I may be able to build those into Raspy or [RaspyGeo](https://github.com/quantum-dan/raspygeo) (which is built around modifying geometry files directly) in the future.  That'll take a bit more time commitment, so I won't guess at a timeline.

**Comment by quantum-dan** [comment]
Okay, I have uploaded a notebook (with a PDF in Releases) with examples covering flow data retrieval, setting roughness, and changing flow profiles, which I believe covers the Raspy end of your workflows as far as currently supported by Raspy.

**Comment by pmd84** [comment]
Quantum Dan you are the man! Thank you for taking the time to put that notebook together. I plan to test it out early next week.

**Comment by johnwick67943532** [comment]
i got you: https://www.youtube.com/watch?v=tYSxMegMHoI
